Config = {}

---------------------------------
-- settings
---------------------------------
Config.Keybind = 'J' -- keybind prompt to open shop


Config.Products = {
    ['normal'] = {
        { name = 'bread', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'water', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
       
		
    },
    ['weapons'] = {
        { name = 'weapon_revolver_cattleman', amount = 10, price = 50, buyPrice = 25, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_revolver_doubleaction', amount = 10, price = 127, buyPrice = 63.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_revolver_lemat', amount = 10, price = 317, buyPrice = 158.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_revolver_navy', amount = 10, price = 275, buyPrice = 137.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_revolver_schofield', amount = 10, price = 192, buyPrice = 96, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_pistol_mauser', amount = 10, price = 600, buyPrice = 300, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_pistol_semiauto', amount = 10, price = 537, buyPrice = 268.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_pistol_volcanic', amount = 10, price = 270, buyPrice = 135, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_rifle_boltaction', amount = 10, price = 216, buyPrice = 108, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_rifle_springfield', amount = 10, price = 156, buyPrice = 78, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_rifle_varmint', amount = 10, price = 72, buyPrice = 36, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_rifle_elephant', amount = 10, price = 500, buyPrice = 250, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_repeater_carbine', amount = 10, price = 90, buyPrice = 45, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_repeater_evans', amount = 10, price = 300, buyPrice = 150, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_repeater_winchester', amount = 10, price = 243, buyPrice = 121.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_repeater_henry', amount = 10, price = 348, buyPrice = 174, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_sniperrifle_rollingblock', amount = 10, price = 411, buyPrice = 205.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_sniperrifle_carcano', amount = 10, price = 456, buyPrice = 228, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'weapon_shotgun_doublebarrel', amount = 10, price = 456, buyPrice = 228, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'weapon_shotgun_sawedoff', amount = 10, price = 456, buyPrice = 228, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_revolver', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_pistol', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_rifle', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_repeater', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_shotgun', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_arrow', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_arrow_fire', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_rifle_elephant', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_rifle_velocity', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_arrow_dynamite', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_shotgun_slug', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_arrow_poison', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_arrow_dynamite ', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_rifle_elephant', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'WEAPON_MELEE_DAVY_LANTERN', amount = 10, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_kit_binoculars', amount = 10, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_bow', amount = 10, price = 15, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_lasso', amount = 20, price = 30, buyPrice = 15, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_lasso_reinforced', amount = 20, price = 30, buyPrice = 15, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_melee_knife', amount = 20, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        
    },
    ['armoury'] = {
        { name = 'weapon_revolver_cattleman', amount = 1, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'weapon_repeater_winchester', amount = 1, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_revolver', amount = 10, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'ammo_box_repeater', amount = 10, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'cage', amount = 10, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'handcuffs', amount = 10, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'lawbook', amount = 10, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['horse'] = {
        { name = 'horse_lantern', amount = 50, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'sugarcube', amount = 50, price = 1, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'trainer_certificate', amount = 10, price = 15, buyPrice = 7.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'saddlebag', amount = 10, price = 10, buyPrice = 5, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'fireshoes', amount = 10, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'wagonrepairkit', amount = 100, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['prison'] = {
        { name = 'bread', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'water', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'cigarette10', amount = 50, price = 2.00, buyPrice = 1.00, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['moonshine'] = {
        { name = 'water', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'beer', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'whiskey', amount = 50, price = 2.00, buyPrice = 1.00, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'cigarette10', amount = 50, price = 2.00, buyPrice = 1.00, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'matches', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'pipe', amount = 50, price = 5.00, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'pipetobacco', amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'moonshine', amount = 50, price = 15.00, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['medic'] = {
        { name = 'bandage', amount = 50, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'splint', amount = 50, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'firstaid', amount = 50, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'fieldbandage', amount = 50, price = 0, buyPrice = 0, maxStock = 100, minQuality = 50, restock = 10 }
		
    },
    ['butcher'] = {
        { name = 'weapon_melee_knife', amount = 100, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'raw_meat', amount = 100, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'salt', amount = 100, price = 7, buyPrice = 3.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['fishmonger'] = {
        { name = 'weapon_fishingrod', amount = 50, price = 10, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_baitbread01x',    amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_baitcorn01x',     amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_baitcheese01x',   amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_baitworm01x',     amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_baitcricket01x',  amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'p_crawdad01x',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_lgoc_spinner_v6',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_finishedragonflylegendary01x',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_finisdfishlurelegendary01x',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_finishdcrawdlegendary01x',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_lgoc_spinner_v4',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'p_lgoc_spinner_v6',      amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'fishtrap',          amount = 50, price = 5.00, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'trapbait',          amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'fish_meat',          amount = 50, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['trapper'] = {
        { name = 'weapon_melee_knife', amount = 10, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'bait_meat', amount = 10, price = 2, buyPrice = 1.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'bait_fish', amount = 10, price = 2, buyPrice = 1.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
	['newsstand'] = {
        { name = 'newspaper', amount = 100, price = 1, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
    },
    ['horsetrainer'] = {
        { name = 'trainer_brush', amount = 10, price = 10, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'trainer_feed',  amount = 10, price = 1.00, buyPrice = 0.50, maxStock = 100, minQuality = 50, restock = 10 },
        { name = 'horse_reviver', amount = 10, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
		{ name = 'wagonrepairkit', amount = 100, price = 5, buyPrice = 2.50, maxStock = 100, minQuality = 50, restock = 10 },
		
    },
	
}
---------------------------------
-- shop locations and blips

-- persistentStock (true/false): enables stock to persist over server restart
---------------------------------
Config.StoreLocations = {
    ---------------------------------
    -- general store
    ---------------------------------
    {
        label = 'Rhodes General Store',
        name = 'gen-rhodes',
        products = 'normal',
        shopcoords = vec3(1329.80, -1294.37, 77.02),
        npccoords = vec4(1329.80, -1294.37, 77.02, 60.72),
        npcmodel = 'u_m_m_rhdgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Valentine General Store',
        name = 'gen-valentine',
        products = 'normal',
        shopcoords = vec3(-322.36, 804.1, 117.88),
        npccoords = vec4(-324.14, 803.51, 117.88, 280.98),
        npcmodel = 'u_m_m_valgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Strawberry General Store',
        name = 'gen-strawberry',
        products = 'normal',
        shopcoords = vector3(-1789.78, -388.15, 160.33),
        npccoords = vec4(-1789.78, -388.15, 160.33, 65.43),
        npcmodel = 'u_m_m_strgenstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg General Store',
        name = 'gen-annesburg',
        products = 'normal',
        shopcoords = vec3(2930.97, 1365.38, 45.20),
        npccoords = vec4(2930.97, 1365.38, 45.20, 252.02),
        npcmodel = 'u_m_m_rhdgenstoreowner_02',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis General Store',
        name = 'gen-stdenis',
        products = 'normal',
        shopcoords = vec3(2859.36, -1202.19, 49.59),
        npccoords = vec4(2859.36, -1202.19, 49.59, 14.85),
        npcmodel = 'u_m_m_nbxgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed General Store',
        name = 'gen-tumbleweed',
        products = 'normal',
        shopcoords = vec3(-5486.04, -2937.99, -0.40),
        npccoords = vec4(-5486.04, -2937.99, -0.40, 131.21),
        npcmodel = 's_m_m_unibutchers_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Armadillo General Store',
        name = 'gen-armadillo',
        products = 'normal',
        shopcoords = vec3(-3687.35, -2623.34, -13.43),
        npccoords = vec4(-3687.35, -2623.34, -13.43, 276.71),
        npcmodel = 'u_m_m_armgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Blackwater General Store',
        name = 'gen-blackwater',
        products = 'normal',
        shopcoords = vec3(-784.77, -1322.15, 43.88),
        npccoords = vec4(-784.77, -1322.15, 43.88, 194.64),
        npcmodel = 'u_m_o_blwgeneralstoreowner_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Van Horn General Store',
        name = 'gen-vanhorn',
        products = 'normal',
        shopcoords = vector3(3025.60, 562.29, 44.72),
        npccoords = vec4(3025.60, 562.29, 44.72, 262.32),
        npcmodel = 's_m_m_unibutchers_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    ---------------------------------
    -- gunsmith
    ---------------------------------
    {
        label = 'Valentine Gunsmith',
        name = 'wep-valentine',
        products = 'weapons',
        shopcoords = vector3(-281.14, 780.73, 119.53),
        npccoords = vec4(-281.17, 778.94, 119.50, 0.59),
        npcmodel = 'u_m_m_valgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Tumbleweed Gunsmith',
        name = 'wep-tumbleweed',
        products = 'weapons',
        shopcoords = vec3(-5506.41, -2963.95, -0.64),
        npccoords = vec4(-5506.41, -2963.95, -0.64, 110.02),
        npcmodel = 'u_m_m_tumgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Saint Denis Gunsmith',
        name = 'wep-stdenis',
        products = 'weapons',
        shopcoords = vec3(2717.14, -1286.90, 49.64),
        npccoords = vec4(2717.14, -1286.90, 49.64, 29.91),
        npcmodel = 'u_m_m_nbxgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Rhodes Gunsmith',
        name = 'wep-rhodes',
        products = 'weapons',
        shopcoords = vec3(1322.31, -1323.02, 77.89),
        npccoords = vec4(1322.31, -1323.02, 77.89, 354.88),
        npcmodel = 'u_m_m_rhdgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
    {
        label = 'Annesburg Gunsmith',
        name = 'wep-annesburg',
        products = 'weapons',
        shopcoords = vector3(2948.42, 1319.44, 44.82),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_gunsmith',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	--[[
	{
        label = 'tumbleweed booze',
        name = 'booze-tumble',
        products = 'booze',
        shopcoords = vector3(-5517.34, -2907.81, -1.75),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'armadillo booze',
        name = 'booze-arm',
        products = 'booze',
        shopcoords = vector3(-3701.43, -2595.21, -13.33),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'black booze',
        name = 'booze-black',
        products = 'booze',
        shopcoords = vector3(-815.75, -1320.64, 43.68),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'val booze',
        name = 'booze-val',
        products = 'booze',
        shopcoords = vector3(-311.74, 806.82, 118.98),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'Rhodes booze',
        name = 'booze-rho',
        products = 'booze',
        shopcoords = vector3(1341.9, -1375.03, 80.48),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'Stden booze',
        name = 'booze-stden',
        products = 'booze',
        shopcoords = vector3(2638.03, -1225.17, 53.38),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'Secret booze',
        name = 'booze-secret',
        products = 'booze',
        shopcoords = vector3(2794.02, -1168.85, 47.93),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	{
        label = 'Vanhorn booze',
        name = 'booze-horn',
        products = 'booze',
        shopcoords = vector3(2948.37, 526.31, 45.33),
        npccoords = vec4(2948.42, 1319.44, 44.82, 79.11),
        npcmodel = 'u_m_m_asbgunsmith_01',
        scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK',
        blipsprite = 'blip_shop_store',
        blipscale = 0.2,
        showblip = true,
        persistentStock = false,
    },
	--]]
	
	

}
